/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccesoResponseDto } from '../model/models';
import { ExcepcionAccesoDto } from '../model/models';
import { ValidarAccesoDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccesosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Registrar excepción para un acceso rechazado
     * 
     * @endpoint post /accesos/{id}/excepcion
     * @param id ID (uuid) del acceso rechazado
     * @param excepcionAccesoDto 
     */
    accesosControllerExcepcion(id: string, excepcionAccesoDto: ExcepcionAccesoDto, extraHttpRequestParams?: any): Observable<AccesoResponseDto>;

    /**
     * Historial de accesos de un socio
     * 
     * @endpoint get /accesos/socio/{socioId}
     * @param socioId ID (uuid) del socio
     */
    accesosControllerFindBySocio(socioId: string, extraHttpRequestParams?: any): Observable<Array<AccesoResponseDto>>;

    /**
     * Listado de accesos del día (para dashboard)
     * 
     * @endpoint get /accesos/hoy
     */
    accesosControllerFindHoy(extraHttpRequestParams?: any): Observable<Array<AccesoResponseDto>>;

    /**
     * Detalle de un acceso
     * 
     * @endpoint get /accesos/{id}
     * @param id ID (uuid) del acceso
     */
    accesosControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<AccesoResponseDto>;

    /**
     * Validar acceso de un socio por DNI (check-in principal)
     * 
     * @endpoint post /accesos/validar
     * @param validarAccesoDto DNI del socio que intenta ingresar
     */
    accesosControllerValidar(validarAccesoDto: ValidarAccesoDto, extraHttpRequestParams?: any): Observable<AccesoResponseDto>;

}
