export * from './accesos.service';
import { AccesosService } from './accesos.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './catalogos.service';
import { CatalogosService } from './catalogos.service';
export * from './membresias.service';
import { MembresiasService } from './membresias.service';
export * from './metricas.service';
import { MetricasService } from './metricas.service';
export * from './negocio.service';
import { NegocioService } from './negocio.service';
export * from './pagos.service';
import { PagosService } from './pagos.service';
export * from './planesMembresia.service';
import { PlanesMembresiaService } from './planesMembresia.service';
export * from './socios.service';
import { SociosService } from './socios.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export const APIS = [AccesosService, AppService, AuthService, CatalogosService, MembresiasService, MetricasService, NegocioService, PagosService, PlanesMembresiaService, SociosService, UsuariosService];
