export * from './accesos.service';
import { AccesosService } from './accesos.service';
export * from './accesos.serviceInterface';
export * from './app.service';
import { AppService } from './app.service';
export * from './app.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './catalogos.service';
import { CatalogosService } from './catalogos.service';
export * from './catalogos.serviceInterface';
export * from './membresias.service';
import { MembresiasService } from './membresias.service';
export * from './membresias.serviceInterface';
export * from './metricas.service';
import { MetricasService } from './metricas.service';
export * from './metricas.serviceInterface';
export * from './negocio.service';
import { NegocioService } from './negocio.service';
export * from './negocio.serviceInterface';
export * from './negocios.service';
import { NegociosService } from './negocios.service';
export * from './negocios.serviceInterface';
export * from './pagos.service';
import { PagosService } from './pagos.service';
export * from './pagos.serviceInterface';
export * from './planesMembresia.service';
import { PlanesMembresiaService } from './planesMembresia.service';
export * from './planesMembresia.serviceInterface';
export * from './socios.service';
import { SociosService } from './socios.service';
export * from './socios.serviceInterface';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export * from './usuarios.serviceInterface';
export const APIS = [AccesosService, AppService, AuthService, CatalogosService, MembresiasService, MetricasService, NegocioService, NegociosService, PagosService, PlanesMembresiaService, SociosService, UsuariosService];
