/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginDto } from '../model/models';
import { LoginResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Iniciar sesión y obtener JWT
     * 
     * @endpoint post /auth/login
     * @param loginDto Credenciales del usuario del staff
     */
    authControllerLogin(loginDto: LoginDto, extraHttpRequestParams?: any): Observable<LoginResponseDto>;

}
