/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateMedioPagoDto } from '../model/models';
import { CreateRubroDto } from '../model/models';
import { CreateTipoMembresiaDto } from '../model/models';
import { MedioPagoResponseDto } from '../model/models';
import { RubroResponseDto } from '../model/models';
import { TipoMembresiaResponseDto } from '../model/models';
import { UpdateMedioPagoDto } from '../model/models';
import { UpdateRubroDto } from '../model/models';
import { UpdateTipoMembresiaDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CatalogosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear medio de pago
     * 
     * @endpoint post /catalogos/medios-pago
     * @param createMedioPagoDto 
     */
    catalogosControllerCreateMedioPago(createMedioPagoDto: CreateMedioPagoDto, extraHttpRequestParams?: any): Observable<MedioPagoResponseDto>;

    /**
     * Crear rubro
     * 
     * @endpoint post /catalogos/rubros
     * @param createRubroDto 
     */
    catalogosControllerCreateRubro(createRubroDto: CreateRubroDto, extraHttpRequestParams?: any): Observable<RubroResponseDto>;

    /**
     * Crear tipo de membresía
     * 
     * @endpoint post /catalogos/tipos-membresia
     * @param createTipoMembresiaDto 
     */
    catalogosControllerCreateTipoMembresia(createTipoMembresiaDto: CreateTipoMembresiaDto, extraHttpRequestParams?: any): Observable<TipoMembresiaResponseDto>;

    /**
     * Desactivar medio de pago (soft delete)
     * 
     * @endpoint patch /catalogos/medios-pago/{id}/desactivar
     * @param id ID (uuid) del medio de pago
     */
    catalogosControllerDesactivarMedioPago(id: string, extraHttpRequestParams?: any): Observable<MedioPagoResponseDto>;

    /**
     * Desactivar rubro (soft delete)
     * 
     * @endpoint patch /catalogos/rubros/{id}/desactivar
     * @param id ID (uuid) del rubro
     */
    catalogosControllerDesactivarRubro(id: string, extraHttpRequestParams?: any): Observable<RubroResponseDto>;

    /**
     * Desactivar tipo de membresía (soft delete)
     * 
     * @endpoint patch /catalogos/tipos-membresia/{id}/desactivar
     * @param id ID (uuid) del tipo de membresía
     * @param negocioId Negocio del tipo de membresía. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    catalogosControllerDesactivarTipoMembresia(id: string, negocioId?: string, extraHttpRequestParams?: any): Observable<TipoMembresiaResponseDto>;

    /**
     * Listar medios de pago activos
     * 
     * @endpoint get /catalogos/medios-pago
     */
    catalogosControllerFindAllMediosPago(extraHttpRequestParams?: any): Observable<Array<MedioPagoResponseDto>>;

    /**
     * Listar todos los medios de pago (incluye inactivos)
     * 
     * @endpoint get /catalogos/medios-pago/admin
     */
    catalogosControllerFindAllMediosPagoAdmin(extraHttpRequestParams?: any): Observable<Array<MedioPagoResponseDto>>;

    /**
     * Listar rubros activos
     * 
     * @endpoint get /catalogos/rubros
     */
    catalogosControllerFindAllRubros(extraHttpRequestParams?: any): Observable<Array<RubroResponseDto>>;

    /**
     * Listar todos los rubros (incluye inactivos)
     * 
     * @endpoint get /catalogos/rubros/admin
     */
    catalogosControllerFindAllRubrosAdmin(extraHttpRequestParams?: any): Observable<Array<RubroResponseDto>>;

    /**
     * Listar tipos de membresía activos del negocio
     * 
     * @endpoint get /catalogos/tipos-membresia
     * @param negocioId Filtra por otro negocio. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    catalogosControllerFindAllTiposMembresia(negocioId?: string, extraHttpRequestParams?: any): Observable<Array<TipoMembresiaResponseDto>>;

    /**
     * Listar todos los tipos de membresía del negocio (incluye inactivos)
     * 
     * @endpoint get /catalogos/tipos-membresia/admin
     * @param negocioId Filtra por otro negocio. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    catalogosControllerFindAllTiposMembresiaAdmin(negocioId?: string, extraHttpRequestParams?: any): Observable<Array<TipoMembresiaResponseDto>>;

    /**
     * Actualizar medio de pago
     * 
     * @endpoint patch /catalogos/medios-pago/{id}
     * @param id ID (uuid) del medio de pago
     * @param updateMedioPagoDto 
     */
    catalogosControllerUpdateMedioPago(id: string, updateMedioPagoDto: UpdateMedioPagoDto, extraHttpRequestParams?: any): Observable<MedioPagoResponseDto>;

    /**
     * Actualizar rubro
     * 
     * @endpoint patch /catalogos/rubros/{id}
     * @param id ID (uuid) del rubro
     * @param updateRubroDto 
     */
    catalogosControllerUpdateRubro(id: string, updateRubroDto: UpdateRubroDto, extraHttpRequestParams?: any): Observable<RubroResponseDto>;

    /**
     * Actualizar tipo de membresía
     * 
     * @endpoint patch /catalogos/tipos-membresia/{id}
     * @param id ID (uuid) del tipo de membresía
     * @param updateTipoMembresiaDto 
     */
    catalogosControllerUpdateTipoMembresia(id: string, updateTipoMembresiaDto: UpdateTipoMembresiaDto, extraHttpRequestParams?: any): Observable<TipoMembresiaResponseDto>;

}
