/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateMembresiaDto } from '../model/models';
import { MembresiaResponseDto } from '../model/models';
import { MembresiasControllerCancelarRequest } from '../model/models';
import { PaginatedMembresiasResponseDto } from '../model/models';
import { RenovarMembresiaDto } from '../model/models';
import { UpdateMembresiaDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MembresiasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Cancelar membresía: pasa el estado a cancelada (única forma junto a /renovar de cambiar estado)
     * 
     * @endpoint post /membresias/{id}/cancelar
     * @param id ID (uuid) de la membresía a cancelar
     * @param membresiasControllerCancelarRequest 
     */
    membresiasControllerCancelar(id: string, membresiasControllerCancelarRequest: MembresiasControllerCancelarRequest, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

    /**
     * Crear nueva membresía para un socio
     * 
     * @endpoint post /membresias
     * @param createMembresiaDto 
     */
    membresiasControllerCreate(createMembresiaDto: CreateMembresiaDto, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

    /**
     * Listar membresías con filtros y paginación
     * 
     * @endpoint get /membresias
     * @param socioId Filtrar por socio
     * @param estado Filtrar por estado
     * @param limit 
     * @param page 
     */
    membresiasControllerFindAll(socioId?: string, estado?: 'activa' | 'vencida' | 'suspendida' | 'cancelada', limit?: number, page?: number, extraHttpRequestParams?: any): Observable<PaginatedMembresiasResponseDto>;

    /**
     * Obtener detalle de una membresía
     * 
     * @endpoint get /membresias/{id}
     * @param id ID (uuid) de la membresía
     */
    membresiasControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

    /**
     * Reanudar membresía: pasa el estado de suspendida a activa
     * Solo válido si la membresía está en estado suspendida. No modifica fecha_inicio ni fecha_fin. Da 409 si la fecha_fin ya pasó o si el socio tiene otra membresía activa: en ambos casos hay que renovar.
     * @endpoint post /membresias/{id}/reanudar
     * @param id ID (uuid) de la membresía a reanudar
     */
    membresiasControllerReanudar(id: string, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

    /**
     * Renovar membresía: cierra la actual como vencida y crea una nueva activa
     * Sin body renueva con el plan actual. Mandando { planId } cambia de plan: vence la membresía actual y crea la nueva con ese plan.
     * @endpoint post /membresias/{id}/renovar
     * @param id ID (uuid) de la membresía a renovar
     * @param renovarMembresiaDto 
     */
    membresiasControllerRenovar(id: string, renovarMembresiaDto?: RenovarMembresiaDto, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

    /**
     * Suspender membresía: pasa el estado de activa a suspendida
     * Solo válido si la membresía está en estado activa. No modifica fecha_inicio ni fecha_fin: el tiempo suspendido no se compensa, así que al reanudar el socio recupera el período que le quedaba. Mientras está suspendida, el acceso al gimnasio queda rechazado.
     * @endpoint post /membresias/{id}/suspender
     * @param id ID (uuid) de la membresía a suspender
     */
    membresiasControllerSuspender(id: string, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

    /**
     * Actualizar fechas de una membresía (no permite cambiar plan, socio ni estado)
     * 
     * @endpoint patch /membresias/{id}
     * @param id ID (uuid) de la membresía
     * @param updateMembresiaDto 
     */
    membresiasControllerUpdate(id: string, updateMembresiaDto: UpdateMembresiaDto, extraHttpRequestParams?: any): Observable<MembresiaResponseDto>;

}
