/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AsistenciaSemanalDto } from '../model/models';
import { IngresosMensualesDto } from '../model/models';
import { MetricasResumenDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MetricasServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Asistencia de los últimos 7 días (accesos permitidos por día)
     * 
     * @endpoint get /metricas/asistencia-semanal
     */
    metricasControllerGetAsistenciaSemanal(extraHttpRequestParams?: any): Observable<Array<AsistenciaSemanalDto>>;

    /**
     * Ingresos de los últimos 6 meses
     * 
     * @endpoint get /metricas/ingresos-mensuales
     */
    metricasControllerGetIngresosMensuales(extraHttpRequestParams?: any): Observable<Array<IngresosMensualesDto>>;

    /**
     * Resumen general: socios activos, ingresos mes, asistencia semana, membresías por vencer
     * 
     * @endpoint get /metricas/resumen
     */
    metricasControllerGetResumen(extraHttpRequestParams?: any): Observable<MetricasResumenDto>;

}
