/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { NegocioResponseDto } from '../model/models';
import { UpdateNegocioDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface NegocioServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Obtener datos del negocio del usuario logueado
     * 
     * @endpoint get /negocio
     */
    negociosControllerFindByCurrentUser(extraHttpRequestParams?: any): Observable<NegocioResponseDto>;

    /**
     * Actualizar nombre y/o rubro del negocio del usuario logueado
     * Reservado a SUPER_ADMIN: la escritura del negocio quedó cerrada para los demás roles. Para editar cualquier cliente usar PATCH /negocios/:id.
     * @endpoint patch /negocio
     * @param updateNegocioDto 
     */
    negociosControllerUpdate(updateNegocioDto: UpdateNegocioDto, extraHttpRequestParams?: any): Observable<NegocioResponseDto>;

}
