/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateNegocioDto } from '../model/models';
import { NegocioAdminResponseDto } from '../model/models';
import { NegociosAdminControllerEliminarRequest } from '../model/models';
import { UpdateNegocioDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface NegociosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear un negocio junto con su primer usuario DUENO (SUPER_ADMIN)
     * Ambas cosas se crean en una sola transacción. El email del dueño es único global en la plataforma.
     * @endpoint post /negocios
     * @param createNegocioDto 
     */
    negociosAdminControllerCreate(createNegocioDto: CreateNegocioDto, extraHttpRequestParams?: any): Observable<NegocioAdminResponseDto>;

    /**
     * Desactivar un negocio (SUPER_ADMIN)
     * Cambia el estado del negocio a inactivo. Prohibido operar sobre el negocio del propio usuario logueado.
     * @endpoint patch /negocios/{id}/desactivar
     * @param id ID (uuid) del negocio
     */
    negociosAdminControllerDesactivar(id: string, extraHttpRequestParams?: any): Observable<NegocioAdminResponseDto>;

    /**
     * Eliminar un negocio y todos sus datos (SUPER_ADMIN)
     * Elimina permanentemente el negocio y TODOS sus datos en cascada. Solo permitido si el negocio está desactivado y el nombre de confirmación coincide exactamente. Prohibido operar sobre el negocio del propio usuario logueado. Orden de borrado: pagos, accesos, membresías, socios, planes, tipos de membresía, usuarios, negocio.
     * @endpoint delete /negocios/{id}
     * @param id ID (uuid) del negocio
     * @param negociosAdminControllerEliminarRequest 
     */
    negociosAdminControllerEliminar(id: string, negociosAdminControllerEliminarRequest: NegociosAdminControllerEliminarRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Listar todos los negocios de la plataforma (SUPER_ADMIN)
     * 
     * @endpoint get /negocios
     */
    negociosAdminControllerFindAll(extraHttpRequestParams?: any): Observable<Array<NegocioAdminResponseDto>>;

    /**
     * Reactivar un negocio (SUPER_ADMIN)
     * Cambia el estado del negocio a activo. Prohibido operar sobre el negocio del propio usuario logueado.
     * @endpoint patch /negocios/{id}/reactivar
     * @param id ID (uuid) del negocio
     */
    negociosAdminControllerReactivar(id: string, extraHttpRequestParams?: any): Observable<NegocioAdminResponseDto>;

    /**
     * Editar un negocio de la plataforma (SUPER_ADMIN)
     * Edita nombre y/o rubro de cualquier cliente. El slug derivado del nombre no se recalcula.
     * @endpoint patch /negocios/{id}
     * @param id ID (uuid) del negocio
     * @param updateNegocioDto 
     */
    negociosAdminControllerUpdate(id: string, updateNegocioDto: UpdateNegocioDto, extraHttpRequestParams?: any): Observable<NegocioAdminResponseDto>;

}
