/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePagoDto } from '../model/models';
import { PaginatedPagosResponseDto } from '../model/models';
import { PagoResponseDto } from '../model/models';
import { UpdatePagoDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PagosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Registrar nuevo pago
     * 
     * @endpoint post /pagos
     * @param createPagoDto 
     */
    pagosControllerCreate(createPagoDto: CreatePagoDto, extraHttpRequestParams?: any): Observable<PagoResponseDto>;

    /**
     * Listar pagos con filtros y paginación
     * 
     * @endpoint get /pagos
     * @param membresiaId Filtrar por membresía
     * @param socioId Filtrar por socio
     * @param limit 
     * @param page 
     */
    pagosControllerFindAll(membresiaId?: string, socioId?: string, limit?: number, page?: number, extraHttpRequestParams?: any): Observable<PaginatedPagosResponseDto>;

    /**
     * Listar historial de pagos de una membresía
     * 
     * @endpoint get /pagos/membresia/{membresiaId}
     * @param membresiaId ID (uuid) de la membresía
     */
    pagosControllerFindByMembresia(membresiaId: string, extraHttpRequestParams?: any): Observable<Array<PagoResponseDto>>;

    /**
     * Listar historial de pagos de un socio
     * 
     * @endpoint get /pagos/socio/{socioId}
     * @param socioId ID (uuid) del socio
     */
    pagosControllerFindBySocio(socioId: string, extraHttpRequestParams?: any): Observable<Array<PagoResponseDto>>;

    /**
     * Obtener detalle de un pago
     * 
     * @endpoint get /pagos/{id}
     * @param id ID (uuid) del pago
     */
    pagosControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<PagoResponseDto>;

    /**
     * Actualizar pago
     * 
     * @endpoint patch /pagos/{id}
     * @param id ID (uuid) del pago
     * @param updatePagoDto 
     */
    pagosControllerUpdate(id: string, updatePagoDto: UpdatePagoDto, extraHttpRequestParams?: any): Observable<PagoResponseDto>;

}
