/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePlanMembresiaDto } from '../model/models';
import { PlanMembresiaResponseDto } from '../model/models';
import { UpdatePlanMembresiaDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlanesMembresiaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear plan de membresía
     * 
     * @endpoint post /planes-membresia
     * @param createPlanMembresiaDto 
     */
    planesMembresiaControllerCreate(createPlanMembresiaDto: CreatePlanMembresiaDto, extraHttpRequestParams?: any): Observable<PlanMembresiaResponseDto>;

    /**
     * Desactivar plan de membresía (soft delete)
     * 
     * @endpoint patch /planes-membresia/{id}/desactivar
     * @param id ID (uuid) del plan
     * @param negocioId Negocio del plan. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    planesMembresiaControllerDesactivar(id: string, negocioId?: string, extraHttpRequestParams?: any): Observable<PlanMembresiaResponseDto>;

    /**
     * Listar planes de membresía activos del negocio
     * 
     * @endpoint get /planes-membresia
     * @param negocioId Filtra por otro negocio. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    planesMembresiaControllerFindAll(negocioId?: string, extraHttpRequestParams?: any): Observable<Array<PlanMembresiaResponseDto>>;

    /**
     * Listar todos los planes de membresía del negocio (incluye inactivos)
     * 
     * @endpoint get /planes-membresia/admin
     * @param negocioId Filtra por otro negocio. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    planesMembresiaControllerFindAllAdmin(negocioId?: string, extraHttpRequestParams?: any): Observable<Array<PlanMembresiaResponseDto>>;

    /**
     * Obtener detalle de un plan de membresía
     * 
     * @endpoint get /planes-membresia/{id}
     * @param id ID (uuid) del plan
     */
    planesMembresiaControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<PlanMembresiaResponseDto>;

    /**
     * Actualizar plan de membresía
     * 
     * @endpoint patch /planes-membresia/{id}
     * @param id ID (uuid) del plan
     * @param updatePlanMembresiaDto 
     */
    planesMembresiaControllerUpdate(id: string, updatePlanMembresiaDto: UpdatePlanMembresiaDto, extraHttpRequestParams?: any): Observable<PlanMembresiaResponseDto>;

}
