/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSocioDto } from '../model/models';
import { PaginatedSociosResponseDto } from '../model/models';
import { SocioResponseDto } from '../model/models';
import { UpdateSocioDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SociosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear nuevo socio
     * 
     * @endpoint post /socios
     * @param createSocioDto 
     */
    sociosControllerCreate(createSocioDto: CreateSocioDto, extraHttpRequestParams?: any): Observable<SocioResponseDto>;

    /**
     * Desactivar socio (soft delete)
     * 
     * @endpoint patch /socios/{id}/desactivar
     * @param id ID (uuid) del socio
     */
    sociosControllerDesactivar(id: string, extraHttpRequestParams?: any): Observable<SocioResponseDto>;

    /**
     * Listar socios con filtros y paginación
     * 
     * @endpoint get /socios
     * @param dni Filtrar por DNI (coincidencia parcial)
     * @param nombre Filtrar por nombre (coincidencia parcial)
     * @param apellido Filtrar por apellido (coincidencia parcial)
     * @param search Búsqueda global por DNI, nombre o apellido
     * @param activo Filtrar por estado activo (true/false)
     * @param estadoMembresia Filtrar por el estado de la membresía MÁS RECIENTE del socio. \&#39;activa\&#39; &#x3D; estado activa con fecha_fin &gt;&#x3D; hoy. \&#39;vencida\&#39; &#x3D; estado vencida, o activa con fecha_fin ya pasada. \&#39;sin_membresia\&#39; &#x3D; el socio nunca tuvo membresía. Se combina con search y activo.
     * @param limit 
     * @param page 
     */
    sociosControllerFindAll(dni?: string, nombre?: string, apellido?: string, search?: string, activo?: boolean, estadoMembresia?: 'activa' | 'vencida' | 'suspendida' | 'cancelada' | 'sin_membresia', limit?: number, page?: number, extraHttpRequestParams?: any): Observable<PaginatedSociosResponseDto>;

    /**
     * Buscar socio por DNI exacto
     * 
     * @endpoint get /socios/buscar/dni/{dni}
     * @param dni DNI exacto del socio
     */
    sociosControllerFindByDni(dni: string, extraHttpRequestParams?: any): Observable<SocioResponseDto>;

    /**
     * Obtener detalle de un socio
     * 
     * @endpoint get /socios/{id}
     * @param id ID (uuid) del socio
     */
    sociosControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<SocioResponseDto>;

    /**
     * Actualizar socio
     * 
     * @endpoint patch /socios/{id}
     * @param id ID (uuid) del socio
     * @param updateSocioDto 
     */
    sociosControllerUpdate(id: string, updateSocioDto: UpdateSocioDto, extraHttpRequestParams?: any): Observable<SocioResponseDto>;

}
