/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUsuarioDto } from '../model/models';
import { UpdateUsuarioDto } from '../model/models';
import { UsuarioResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsuariosServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Crear nuevo usuario (staff)
     * 
     * @endpoint post /usuarios
     * @param createUsuarioDto 
     */
    usuariosControllerCreate(createUsuarioDto: CreateUsuarioDto, extraHttpRequestParams?: any): Observable<UsuarioResponseDto>;

    /**
     * Desactivar usuario (soft delete)
     * 
     * @endpoint patch /usuarios/{id}/desactivar
     * @param id ID (uuid) del usuario
     * @param negocioId Negocio del usuario. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    usuariosControllerDesactivar(id: string, negocioId?: string, extraHttpRequestParams?: any): Observable<UsuarioResponseDto>;

    /**
     * Listar usuarios del negocio
     * 
     * @endpoint get /usuarios
     * @param negocioId Negocio a listar. Solo SUPER_ADMIN; otros roles usan el del token.
     */
    usuariosControllerFindAll(negocioId?: string, extraHttpRequestParams?: any): Observable<Array<UsuarioResponseDto>>;

    /**
     * Obtener detalle de un usuario
     * 
     * @endpoint get /usuarios/{id}
     * @param id ID (uuid) del usuario
     */
    usuariosControllerFindOne(id: string, extraHttpRequestParams?: any): Observable<UsuarioResponseDto>;

    /**
     * Actualizar usuario
     * 
     * @endpoint patch /usuarios/{id}
     * @param id ID (uuid) del usuario
     * @param updateUsuarioDto 
     */
    usuariosControllerUpdate(id: string, updateUsuarioDto: UpdateUsuarioDto, extraHttpRequestParams?: any): Observable<UsuarioResponseDto>;

}
