/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccesoResponseDto { 
    id: string;
    socioId?: string;
    socioNombre?: string;
    socioDni?: string;
    fechaHora: string;
    resultado: AccesoResponseDto.ResultadoEnum;
    observacion: string;
    autorizadoPorId?: string;
    autorizadoPorNombre?: string;
    fechaCreacion: string;
}
export namespace AccesoResponseDto {
    export const ResultadoEnum = {
        Permitido: 'permitido',
        Rechazado: 'rechazado',
        Excepcion: 'excepcion'
    } as const;
    export type ResultadoEnum = typeof ResultadoEnum[keyof typeof ResultadoEnum];
}


