/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUsuarioDto { 
    email: string;
    password: string;
    rol: CreateUsuarioDto.RolEnum;
}
export namespace CreateUsuarioDto {
    export const RolEnum = {
        SuperAdmin: 'super_admin',
        Dueno: 'dueno',
        Administrador: 'administrador',
        Recepcionista: 'recepcionista'
    } as const;
    export type RolEnum = typeof RolEnum[keyof typeof RolEnum];
}


