/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSocioDto { 
    dni: string;
    nombre: string;
    apellido: string;
    telefono?: string;
    fechaAlta: string;
}

