/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsuarioLoginDto } from './usuarioLoginDto';


export interface LoginResponseDto { 
    /**
     * Token JWT. Debe enviarse en el header Authorization: Bearer <token>
     */
    accessToken: string;
    user: UsuarioLoginDto;
}

