/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MembresiasControllerRenovarRequest { 
    /**
     * Nuevo plan para la membresía renovada (opcional; si no se envía, se mantiene el mismo plan)
     */
    planId?: string;
}