/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NegocioResponseDto { 
    id: string;
    nombre: string;
    activo: boolean;
    rubroId: string;
    rubroNombre: string;
}

