/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SocioResponseDto } from './socioResponseDto';


export interface PaginatedSociosResponseDto { 
    /**
     * Cantidad total de registros que cumplen el filtro
     */
    total: number;
    /**
     * Socios de la página actual
     */
    data: Array<SocioResponseDto>;
}

