/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MembresiaResponseDto } from './membresiaResponseDto';


export interface PaginatedMembresiasResponseDto { 
    /**
     * Cantidad total de registros que cumplen el filtro
     */
    total: number;
    /**
     * Membresías de la página actual
     */
    data: Array<MembresiaResponseDto>;
}

