/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResumenMembresiaDto { 
    /**
     * ID de la membresía más reciente
     */
    id: string;
    /**
     * ID del plan
     */
    planId: string;
    /**
     * Nombre del plan (el de su tipo de membresía)
     */
    planNombre: string;
    estado: ResumenMembresiaDto.EstadoEnum;
    /**
     * Fecha de fin (vencimiento)
     */
    fechaFin: string;
}
export namespace ResumenMembresiaDto {
    export const EstadoEnum = {
        Activa: 'activa',
        Vencida: 'vencida',
        Suspendida: 'suspendida',
        Cancelada: 'cancelada'
    } as const;
    export type EstadoEnum = typeof EstadoEnum[keyof typeof EstadoEnum];
}


