/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SocioResponseDto { 
    id: string;
    dni: string;
    nombre: string;
    apellido: string;
    telefono: string;
    fechaAlta: string;
    activo: boolean;
    negocioId: string;
    fechaCreacion: string;
    fechaActualizacion: string;
    membresiaActiva?: object;
}

