/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdatePlanMembresiaDto { 
    diasPorSemana?: number;
    duracionDias?: number;
    precio?: number;
    tipoMembresiaId?: string;
}

