/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateNegocioDto { 
    nombre?: string;
    rubroId?: string;
    direccion?: string;
    telefono?: string;
    email?: string;
    horarios?: string;
    logo?: string;
}

