/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateMembresiaDto { 
    socioId?: string;
    planId?: string;
    fechaInicio?: string;
    fechaFin?: string;
    estado?: UpdateMembresiaDto.EstadoEnum;
}
export namespace UpdateMembresiaDto {
    export const EstadoEnum = {
        Activa: 'activa',
        Vencida: 'vencida',
        Suspendida: 'suspendida',
        Cancelada: 'cancelada'
    } as const;
    export type EstadoEnum = typeof EstadoEnum[keyof typeof EstadoEnum];
}


