/**
 * Control Ingreso API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioLoginDto { 
    /**
     * ID del usuario
     */
    id: string;
    email: string;
    /**
     * Rol del usuario
     */
    rol: UsuarioLoginDto.RolEnum;
    /**
     * ID del negocio al que pertenece
     */
    negocioId: string;
}
export namespace UsuarioLoginDto {
    export const RolEnum = {
        SuperAdmin: 'super_admin',
        Dueno: 'dueno',
        Administrador: 'administrador',
        Recepcionista: 'recepcionista'
    } as const;
    export type RolEnum = typeof RolEnum[keyof typeof RolEnum];
}


